import './globals.css'

import type { Metadata } from 'next'

import { nunito } from './font'

export const metadata: Metadata = {
  title: 'Woovi',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="pt">
      <body className={nunito.className}>{children}</body>
    </html>
  )
}

export default RootLayout
